// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_1vuni0fn3BzMhzCOJoR0eCiBQXC3RHM',
    appId: '1:1022721007664:web:50b899de49db9a584a0df5',
    messagingSenderId: '1022721007664',
    projectId: 'task-manager-df200',
    authDomain: 'task-manager-df200.firebaseapp.com',
    storageBucket: 'task-manager-df200.firebasestorage.app',
    measurementId: 'G-LS3L5S4J50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc16Vb6fn8gHdo1xXW142YDwFzBS43O4k',
    appId: '1:1022721007664:android:08e2b98142c3c0e54a0df5',
    messagingSenderId: '1022721007664',
    projectId: 'task-manager-df200',
    storageBucket: 'task-manager-df200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHbFgrqWGKQ5fdFHytKmxXO8Mg7h_Ub7k',
    appId: '1:1022721007664:ios:965eac3159e513e04a0df5',
    messagingSenderId: '1022721007664',
    projectId: 'task-manager-df200',
    storageBucket: 'task-manager-df200.firebasestorage.app',
    iosBundleId: 'com.rambhola.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHbFgrqWGKQ5fdFHytKmxXO8Mg7h_Ub7k',
    appId: '1:1022721007664:ios:965eac3159e513e04a0df5',
    messagingSenderId: '1022721007664',
    projectId: 'task-manager-df200',
    storageBucket: 'task-manager-df200.firebasestorage.app',
    iosBundleId: 'com.rambhola.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_1vuni0fn3BzMhzCOJoR0eCiBQXC3RHM',
    appId: '1:1022721007664:web:deefa25bc4373b7f4a0df5',
    messagingSenderId: '1022721007664',
    projectId: 'task-manager-df200',
    authDomain: 'task-manager-df200.firebaseapp.com',
    storageBucket: 'task-manager-df200.firebasestorage.app',
    measurementId: 'G-9WVN9F5MW3',
  );
}
